version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
   
     - ./outputs:/app/outputs

     
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
  worker:
    build: .
    command: celery -A app.celery_worker.app worker --loglevel=info -Q default
    depends_on:
      - redis
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
